### PR TITLE
Add CF killer to Skillshare

### PR DESCRIPTION
**Pull request by LikDev-256**
Haven't tested feel free to test it before merge I'm in an impossible situation to test it and even if I could Skillshare IP blocked me for no reason.

The builds fail in GH actions bcz of some unknown reason something to do with the git command failing

### CODE REVIEW

**Comment by Blatzar** [comment]
Im getting infinite loading on homepage with this :skull: 
@LikDev-256

**Comment by LikDev-256** [comment]
> Im getting infinite loading on homepage with this 💀 @LikDev-256

Ah looks like cloudflare wasn't the issue

**Comment by Blatzar** [comment]
Closing this then :pensive:

**Comment by LikDev-256** [comment]
> Closing this then 😔

No problemo 🙃
I'll try to fix the issue later.
CF killer was just a guess bcz I was have CF redirects

**Pull request closed without merging**
